openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation for My Contacts App
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw7-swagger-yhrl.onrender.com
paths:
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
